package(default_visibility = ["//visibility:public"])

cc_proto_library(
    name = "sensors_cc_proto",
    deps = [
        ":sensors_proto",
    ],
)

proto_library(
    name = "sensors_proto",
    srcs = [
        "sensors.proto",
    ],
)
