package(default_visibility = ["//visibility:public"])

cc_proto_library(
    name = "perception_cc_proto",
    deps = [
        ":perception_proto_lib",
    ],
)

proto_library(
    name = "perception_proto_lib",
    srcs = [
        "perception.proto",
    ],
)
