package(default_visibility = ["//visibility:public"])

cc_proto_library(
    name = "status_cc_proto",
    deps = [
        ":status_proto",
    ],
)

proto_library(
    name = "status_proto",
    srcs = [
        "status.proto",
    ],
)
