package(default_visibility = ["//visibility:public"])

cc_proto_library(
    name = "sensors_cc_proto",
    deps = [
        ":sensors_proto",
    ],
)

proto_library(
    name = "sensors_proto",
    srcs = [
        "sensors.proto",
    ],
)

cc_proto_library(
    name = "control_cc_proto",
    deps = [
        ":control_proto",
    ],
)

proto_library(
    name = "control_proto",
    srcs = [
        "control.proto",
    ],
)

cc_proto_library(
    name = "localization_cc_proto",
    deps = [
        ":localization_proto",
    ],
)
proto_library(
    name = "localization_proto",
    srcs = [
        "localization.proto",
    ],
)

cc_proto_library(
    name = "planning_cc_proto",
    deps = [
        ":planning_proto",
    ],
)
proto_library(
    name = "planning_proto",
    srcs = [
        "planning.proto",
    ],
)
