package(default_visibility = ["//visibility:public"])

cc_proto_library(
    name = "localization_cc_proto",
    deps = [
        ":localization_proto",
    ],
)

proto_library(
    name = "localization_proto",
    srcs = [
        "localization.proto",
    ],
)
