package(default_visibility = ["//visibility:public"])

cc_proto_library(
    name = "control_cc_proto",
    deps = [
        ":control_proto_lib",
    ],
)

proto_library(
    name = "control_proto_lib",
    srcs = [
        "chassis.proto",
        "control.proto",
    ],
)
